# 연산함수

- 연산함수
  - 배열 내부 연산을 지원하는 함수
  - 축(axis)
    - 배열의 랭크가 증가할 때 마다 새로운 축이 추가되어 차원 증가


In [ ]:
import numpy as np

In [ ]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 함수를 랭크가 2 이상인 배열에 적용할 때 축으로 연산의 방향을 설정
- 예를들면 axis=0은 행방향(위에서 아래로), axis=1 은 열방향(왼쪽에서 오른쪽으로)


In [7]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [8]:
test_array.sum(axis=1)

array([10, 26, 42])

In [9]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [10]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [11]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [12]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [13]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [14]:
test_array.std()  # 전체 값에 대한 표준편차 연산

np.float64(3.452052529534663)

In [15]:
test_array.std(axis=0)  # axis=0 축을 기준으로 표준편차 연산

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [ ]:
np.sqrt(test_array)  # 각 요소에 제곱근 연산 수행

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

- 연결함수
  - 두 객체간의 결합을 지원하는 함수
  - vstack 함수
    - 배열을 수직으로 붙여 하나의 행렬을 생성
  - hstack 함수
    - 배열을 수평으로 붙여 하나의 행렬을 생성


In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [18]:
np.vstack((v1, v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.hstack((v1, v2))

array([1, 2, 3, 4, 5, 6])

- numpy가 기본적으로 열벡터를 지원하지 않아 행렬로 표현


In [20]:
v1 = v1.reshape(-1, 1)
v2 = v2.reshape(-1, 1)

In [21]:
v1

array([[1],
       [2],
       [3]])

In [22]:
v2

array([[4],
       [5],
       [6]])

In [23]:
np.hstack((v1, v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

- 연결함수
  - concatenate 함수
    - 축을 고려하여 두 개의 배열을 결합
    - 스택(stack) 계열의 함수와 다리 생성될 배열과 소스가 되는 배열의 차원이 같아야 함
    - 두 벡터를 결합하고 싶다면, 해당 벡터를 일단 2차원 배열 꼴로 변환 후 행렬로 나타내야 함
      - v1과 v2 모두 사실상 행렬이지만 벡터의 형태
      - 매개변수 axis=0로 행을 기준으로 연결


In [28]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4, 5, 6]])
np.concatenate((v1, v2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
v1 = np.array([1, 2, 3, 4]).reshape(2, 2)
v2 = np.array([[5, 6]]).T
v1

array([[1, 2],
       [3, 4]])

In [30]:
v2

array([[5],
       [6]])

In [31]:
np.concatenate((v1, v2), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])