# 사칙연산

- 넘파이는 파이썬과 동일하게 배열 간 사칙연산 지원
  - 행렬과 행렬, 벡터와 벡터 간 사칙연산이 가능
- 같은 배열의 구조일 때 요소별 연산(element-wise operation)
  - 요소별 연산 : 두 배열의 구조가 동일할 경우 같은 인덱스 요소들 끼리 연산


In [1]:
import numpy as np


In [ ]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [4]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x**x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

# 배열 간의 곱셈

- 배열 간의 곱셈에서는 요소별 연산과 벡터의 내역 연산 가능
- 백터의 내적
  - 두 배열 간의 곱셈
- 두 개의 행렬에서 첫 번째 행렬의 열 크기와 두 번째 행렬의 행 크기가 동일해야 함
- m*n 행렬 n*l 행렬, 벡터의 내적 연산하면 m\*l의 행렬을 생성


# 벡터의 내적 연산

- dot 함수
  - 벡터의 내적 연산
  - 2*3 행렬과 3*2 행렬의 연산 결과는 2\*2 행렬


In [7]:
x_1 = np.arange(1, 7).reshape(2, 3)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
x_2 = np.arange(1, 7).reshape(3, 2)
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

# 브로드캐스팅 연산

- 하나의 행렬과 스칼라 값들 간 연산이나 행렬과 벡터 간의 연산
- 방송국의 전파가 퍼지듯 뒤에 있는 스칼라 값이 모든 요소에 퍼지듯이 연산


In [ ]:
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [12]:
x - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [13]:
x // 3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]])

In [ ]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
x = np.arange(1, 13).reshape(4, 3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
v = np.arange(10, 40, 10)
v

array([10, 20, 30])

In [17]:
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])