# 비교연산

- 연산 결과는 항상 불린형을 가진 배열로 추출
- 브로드캐스팅 비교 연산
  - 하나의 스칼라 값과 벡터 간의 비교 연산은 벡터 내 전체 요소에 적용


In [1]:
import numpy as np

In [2]:
x = np.array([4, 3, 2, 6, 8, 5])
x > 3

array([ True, False, False,  True,  True,  True])

- 요소별 비교 연산
  - 두 개의 배열 간 배열의 구조(shape)가 동일한 경우
  - 같은 위치에 있는 요소들끼리 비교 연산
  - [1 > 2, 3> 1, 0 > 7]과 같이 연산이 실시된 후 이를 반환


In [3]:
x = np.array([1, 3, 0])
y = np.array([2, 1, 7])
x > y

array([False,  True, False])

- all 함수
  - 배열 내부의 모든 값이 참일 때는 True, 하나라도 참이 아닐 경우에는 False를 반환
  - and 조건을 전체 요소에 적용
- any 함수
  - 배열 내부의 값 중 하나라도 참일 때는 True, 모두 거짓을 경우 False를 반환
  - or 조건을 전체 요소에 적용


In [4]:
x = np.array([4, 6, 7, 3, 2])
(x > 3)

array([ True,  True,  True, False, False])

In [5]:
(x > 3).all()

np.False_

In [6]:
(x > 3).any()

np.True_

In [7]:
(x < 10).any()

np.True_

In [8]:
(x < 10).all()

np.True_

In [9]:
(x > 10).any()

np.False_

- where 함수
  - 배열이 불린형으로 이루어졌을 때 참인 값들의 인덱스를 반환
  - x > 5를 만족하는 값은 6과 7
  - 6과 7의 인덱스 값인 [1,2]를 반환
  - True/False 대신 참/거짓인 경우의 값을 지정할 수 있음
  - 참일 경우에 10을 거짓일 경우에 20을 반환


In [10]:
x = np.array([4, 6, 7, 3, 2])
x > 5

array([False,  True,  True, False, False])

In [11]:
np.where(x > 5)

(array([1, 2]),)

In [12]:
np.where(x > 5, 10, 20)

array([20, 10, 10, 20, 20])

- 정렬된 값의 인덱스를 반환해주는 함수
  - argsort : 배열 내 값들을 작은 순서대로 인덱스를 반환
  - argmax : 배열 내 값들 중 가장 큰 값의 인덱스를 반환
  - argmin : 배열 내 값들 중 가장 작은 값의 인덱스를 반환


In [13]:
x = np.array([4, 6, 7, 3, 2])
np.argsort(x)

array([4, 3, 0, 1, 2])

In [14]:
np.argmax(x)

np.int64(2)

In [15]:
np.argmin(x)

np.int64(4)

# 인덱스를 활용한 데이터 추출

- 불린 인덱스
  - 배열에 있는 값들을 반환할 특정 조건을 불린형의 배열에 넣어서 추출
  - 인덱스에 들어가는 배열은 불린형이어야 함
  - 불린형 배열과 추출 대상이 되는 배열의 구조가 같아야 함


In [16]:
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [17]:
cond = x > 3
x[cond]

array([4, 6, 7])

In [18]:
x.shape

(5,)

In [19]:
cond.shape

(5,)

- 팬시 인덱스
  - 정수형 배열의 값을 사용하여 해당 정수의 인덱스에 위치한 값을 반환
  - 인덱스 항목에 넣을 배열은 정수로만 구성되어야 함
  - 정수 값의 범위는 대상이 되는 배열이 가지는 인덱스의 범위 내 대상이 되는 배열과 인덱스 배열의 구조(shape)가 같은 필요는 없음


In [20]:
x = np.array([4, 6, 7, 3, 2])
cond = np.array([1, 2, 0, 2, 2, 2])
x[cond]

array([6, 7, 4, 7, 7, 7])

In [21]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [23]:
x = np.array([[1, 4], [9, 16]], int)
a = np.array([0, 1, 1, 1, 0, 0], int)
b = np.array([0, 0, 0, 1, 1, 1], int)
x[a, b]

array([ 1,  9,  9, 16,  4,  4])