In [1]:
import numpy as np

np_array = np.array([1, 4, 5, 8], float)
print(np_array.shape)

(4,)


# 넘파이 배열 구조

- 배열의 구조(shape)
  - 1차원 4개의 요소를 가지고 있을때


In [12]:
tensor_rank3 = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
]

tarray = np.array(tensor_rank3, float)
tarray.shape

(2, 3, 4)

- 뒤에 있는 값일 수록 낮은 rank의 값


In [13]:
print(tarray.ndim)
print(tarray.size)

3
24


- ndim : 차원수
- size : 넘파이 배열에 있는 모든 데이터의 수


## 배열의 데이터 타입

- dtype으로 넘파이 배열의 데이터 타입 지정
  - 변수가 사용하는 메모리 크기가 정해짐
  - itemsize 요소(property)로 넘파이 배열에서 각 요소가 차지하는 바이트 확인


In [14]:
tarray.itemsize

8

In [18]:
np.array([1, 2, 3], dtype=np.float32).itemsize

4

- 배열의 구조 다루기
  - reshape 함수로 배열의 구조를 변경하고 랭크를 조절


In [19]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [20]:
x.reshape(-1)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [21]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
x.reshape(2, 2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [27]:
x = np.array(range(8)).reshape(4, 2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [28]:
x.reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
x.reshape(2, 2, -1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

- -1을 사용하면 나머지 차원의 크기를 지정했을때, 전체 요소의 개수를 고려하여 마지막 차원 자동 지정


- flatten 함수는 데이터 그대로 1차원으로 변경


In [ ]:
print(x.shape)
x.flatten()

(4, 2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])