# 인덱싱

- 리스트에 있는 값의 상대적인 주소로 값에 접근
- 넘파이 배열의 인덱스에는 콤마를 지원 [행][열] 또는 [행, 열]
- 3차원 텐서 이상은 shape에서 출력되는 랭크 순서대로 인덱싱에 접근


In [1]:
import numpy as np

X = np.array([[1, 2, 3], [4, 5, 6]], int)
X

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
X[0][0]

np.int64(1)

In [3]:
X[0, 2]

np.int64(3)

In [4]:
X[0, 1] = 100
X

array([[  1, 100,   3],
       [  4,   5,   6]])

# 슬라이싱

- 인덱스를 사용하여 리스트 일부를 잘라내여 반환
- 넘파이 배열은 행과 열을 나눠 슬라이싱 할수 있음


In [5]:
X = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
X[:, 2:]  # 전체 행의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [6]:
X[1, 1:3]  # 1행의 1열~2열

array([7, 8])

## 증가값

- 리스트에서 데이터의 요소를 호출할 때 데이터를 건너뛰면서 반환
- [시작 인덱스:마지막 인덱스: 증가값] 형태
- 각 랭크에 있는 요소별로 모두 적용할 수 있음


In [7]:
X = np.array(range(15), int).reshape(3, -1)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
X[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [9]:
X[::2, ::3]

array([[ 0,  3],
       [10, 13]])

# 배열 생성 함수

- arange
  - range 함수와 같이 차례대로 값을 생성
  - (시작인덱스, 마지막 인덱스, 증가값) 으로 구성
  - range 함수와 달리 증가값에 실수형이 입력되어도 값을 생성할 수 있음
  - 소수점 값을 주기적으로 생성할 때 유용


In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [13]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## ones, zeros, empty

- ones 함수
  - 1로만 구성된 넘파일 배열을 생성
  - 사전에 shape 값을 넣어서 원하는 크기의 넘파이 배열 생성
- zeros 함수
  - 0으로만 구성된 넘파이 배열을 생성
- empty 함수
  - 활용 가능한 메모리 공간 확보하여 반환
  - ones, zeros는 먼저 shape의 크기만큼 메모리를 할당하고 그곳에 값을 채움
  - 해당 메모리 공간에 값이 남았을 경우 그 값을 함께 반환
  - empty는 메모리 초기화 않아 생성될 때마다 다른 값 반환
- 생성 시점에서 dtype을 지정해주면 해당 데이터 타입으로 배열 생성


In [14]:
np.ones(shape=(5, 2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [15]:
np.zeros(shape=(2, 2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [16]:
np.empty(shape=(2, 4), dtype=np.float32)

array([[ 0.0000000e+00,  0.0000000e+00, -1.5588366e+13,  8.4498297e-43],
       [-1.5587946e+13,  8.4498297e-43, -1.5588114e+13,  8.4498297e-43]],
      dtype=float32)

# 통계 분석 함수

- uniform 함수
  - 균등분포 함수
  - np.random.uniform(시작값, 끝값, 데이터개수)
- normal 함수
  - 정규분포 함수
  - np.random.normal(평균값, 분산, 데이터개수)


In [17]:
np.random.uniform(0, 5, 10)

array([4.95917516, 3.69454039, 1.42894984, 4.39881328, 3.96527081,
       4.44511553, 4.38915159, 3.14841382, 3.20073925, 0.93819971])

In [18]:
np.random.normal(0, 2, 10)

array([ 2.08489253, -0.73192142, -0.67577129, -0.54869733,  3.92417658,
        1.84717712,  2.70791929, -0.69944567, -2.19982962, -1.45179085])